import {
  Accordion,
  AccordionButton,
  AccordionItem,
  AccordionPanel,
  Box,
  ListItem,
  OrderedList,
  Text,
  useColorMode,
  AccordionIcon,
  Heading,
  Image,
  UnorderedList,
} from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";

function Faq() {
  const { colorMode, toggleColorMode } = useColorMode();

  const accordianHeight = 20;
  const highlightColor = colorMode === "light" ? "brand.400" : "brand.500";
  const highlightTextColor = colorMode === "light" ? "black" : "white";

  const accordionButtonStyle = {
    // borderWidth: 1,
    // borderRadius: "8px",
    // height: variant
  };

  return (
    <div>
      
    </div>
  )

  return (
    <div>
      <Head>
        <title>FAQ | duckDAO</title>
        <meta property="og:image" content={"/android-chrome-512x512.png"} />
        <meta
          name="description"
          content="duckDAO | The duckpools protocol DAO. Vote and view QUACKS metrics using the duckDAO."
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box mb="8">
        <Heading fontSize={"3xl"} textAlign="center">
          🦆 General FAQ
        </Heading>
      </Box>

      <Box>
        <Accordion fontSize={"lg"} allowToggle>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  What is duckpools?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              duckpools is a lending protocol offering algorithmic lending pools
              and collateralized loans! <br />
              Lenders can provide capital to lending pools to earn passive
              income. <br />
              Borrowers can obtain funds from these lending pools through
              collateralized loans. <br />
            </AccordionPanel>
          </AccordionItem>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  Is duckpools open-source?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              duckpools is open-sourced and decentralized. Find us on github
              here:{" "}
              <Text color={colorMode === "light" ? "brand.600" : "brand.400"}>
                <a
                  rel="noreferrer"
                  href="https://github.com/duckpools"
                  target={"_blank"}
                  color="orange"
                >
                  https://github.com/duckpools
                </a>
              </Text>
            </AccordionPanel>
          </AccordionItem>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  Why is the borrowing interest rate different to the lending
                  APY on duckpools?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text mb="2">
                Borrowing and lending interest rates are variable based on the
                utility of the pool. The specific value of these rates is
                determine by the utility of the pool using algorithmic smart
                contracts. Lenders actually receive the entirety of a borrower
                {"'"}s interest repayments, however within a pool we must
                consider that not all the assets are lent out and as such the
                effective return to lenders will only be a portion of the total
                possible interest generated by the borrowing rate. That is
                Lender Yield = Borrow Rate * Pool Utility.
                <br /> <br />
                The borrowing interest rate on duckpools is governed by the pool
                {"'"}s automated algorithm based on the utility (percentage of
                pool assets lent out) of the pool. Whilst the entirety of
                borrower interest repayments go to the lending pool, the
                effective APY will only be a portion of the borrowing rate.
                Specifically it will be lend APY = borrow rate * pool utility.
              </Text>
            </AccordionPanel>
          </AccordionItem>

          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  Which algorithm determines the interest rates on duckpools.io?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text>
                The interest rate for each pool on duckpools.io is governed by
                the pool{"'"}s utility. Essentially, as the utility (or
                percentage of assets lent out) increases, so does the interest
                rate. For a visual representation of how the annual interest
                rate varies with different pool utilizations, please refer to
                the provided graph below:
                <Text color={colorMode === "light" ? "brand.600" : "brand.400"}>
                  <a
                    rel="noreferrer"
                    href="https://www.desmos.com/calculator/jwkn3c9dhz"
                    target={"_blank"}
                    color="orange"
                  >
                    https://www.desmos.com/calculator/g7n0qvfvih
                  </a>
                </Text>
              </Text>
            </AccordionPanel>
          </AccordionItem>
        </Accordion>

        <Heading my={8} fontSize={"2xl"} textAlign="center">
          🤝 FAQ | Lending
        </Heading>

        <Accordion fontSize={"lg"} allowToggle>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  What are the risks of lending?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text mb={4} fontSize={"xl"}>
                There are two predominant risks in lending:
              </Text>
              <UnorderedList spacing={4}>
                <ListItem>
                  Liquidation Risk: Liquidation risk is the risk of a borrower
                  {"'"}s collateral being liquidated at a value less than the
                  amount they borrowed, leaving the pool at a loss. This loss is
                  shared equally among all lenders of the pool (proportional to
                  the amount lent). The loss occurs when the value of the
                  borrower{"'"}s collateral crashes too quickly and plummets
                  below the amount lent before open-source off-chain bots can
                  liquidate the loan. You can assess this risk by considering
                  the pool{"'"}s accepted forms of collateral and their
                  liquidation thresholds. Pools with less volatile assets
                  (assets that are less likely to crash dramatically) and pools
                  with higher liquidation thresholds (the point when off-chain
                  bots are allowed to liquidate loans) are less likely to have
                  liquidation losses.
                </ListItem>
                <ListItem>
                  Smart Contract Risk: As with any emerging DeFi protocol,
                  another risk to duckpools lenders is smart contract risk,
                  specifically flaws in the contract design or implementation.
                  The duckpools protocol has undergone multiple security reviews
                  and stages of testing. Further, the entire protocol code-base
                  is open-source and available on GitHub. However, it is still
                  necessary to highlight the risk.
                </ListItem>
              </UnorderedList>
            </AccordionPanel>
          </AccordionItem>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  Can I withdraw my lent assets at any time?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text mb={2}>
                You can withdraw your assets from a lending pool at any time,
                provided there is still sufficient liquidity in the pool.
                Liquidity, here, refers to the amount of unborrowed assets in
                the pool.
              </Text>
              <Text>
                There is no penalty for withdrawing, but there are inbound and
                outbound fees. You can find the fee schedule for each pool
                linked here:
              </Text>
              <Text color={colorMode === "light" ? "brand.600" : "brand.400"}>
                <a
                  rel="noreferrer"
                  href="https://duckpools.notion.site/duckpools/4b5df7ab8bc54e3bad182221be65c69a?v=3afd7d81ab464fcd9afd9f5f989503c0&p=fbbc3881dd6d496b8ce9c2ea39c0770d&pm=s"
                  target={"_blank"}
                >
                  {`https://duckpools.notion.site/duckpools/4b5df7ab8bc54e3bad182221be65c69a?v=3afd7d81ab464fcd9afd9f5f989503c0&p=fbbc3881dd6d496b8ce9c2ea39c0770d&pm=s`}
                </a>
              </Text>
            </AccordionPanel>
          </AccordionItem>
        </Accordion>

        <Heading my={8} fontSize={"2xl"} textAlign="center">
          🥚 FAQ | Borrowing
        </Heading>

        <Accordion fontSize={"lg"} allowToggle>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  Why borrow on duckpools.io?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text mb={2}>
                Borrowing is a powerful financial tool. duckpools.io stands out
                as the only platform allowing instant loans using Ergo and its
                native assets as collateral. If you own ERG or supported Ergo
                assets, then the creation of duckpools has likely increased your
                borrowing power.
              </Text>
              <Text mb={2}>
                Some common use cases of borrowing on duckpools include:
              </Text>
              <UnorderedList spacing={4} mb={4}>
                <ListItem>
                  Trading and leverage: duckpools loans can be used to enter
                  short and long positions on supported Ergo assets.
                </ListItem>
                <ListItem>
                  Capitalizing on opportunities: Unlock instant liquidity for
                  timely investments into promising new Ergo startups,
                  undervalued NFTs, arbitrage opportunities, or even funding
                  your own business activities.
                </ListItem>
                <ListItem>
                  Debt management: Utilize your Ergo and native assets as
                  collateral to borrow at competitive rates on duckpools.io,
                  potentially allowing you to pay off higher interest
                  liabilities or consolidate debts.
                </ListItem>
                <ListItem>
                  Unexpected Expenses: Cover unforeseen financial challenges
                  without liquidating your holdings.
                </ListItem>
              </UnorderedList>
              <Text>
                duckpools allows its user to obtain working capital enabling
                their financial needs, all without selling their assets.
              </Text>
            </AccordionPanel>
          </AccordionItem>

          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  How do I select how much collateral to supply when borrowing?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text mb={2}>
                On duckpools.io, you can choose a collateralization level of
                135%, 150%, or 170%. This ratio indicates how much collateral
                you must offer compared to your loan amount.
                <br />
                <br />
                For example, borrowing 100 SigUSD at 135% means providing 135
                SigUSD in assets as collateral. Using a lower ratio makes your
                loan riskier and closer to the liquidation threshold. This
                choice requires more active monitoring. Opting for a higher
                ratio offers greater safety from potential liquidation.
              </Text>
            </AccordionPanel>
          </AccordionItem>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  Can I change the adjust the amount of collateral used to
                  secure my loan after borrowing?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text mb={2}>
                Yes! You can adjust the collateral on your loan at anytime,
                provided the adjustment is still above the liquidation threshold
                for your loan.
              </Text>
            </AccordionPanel>
          </AccordionItem>
          <AccordionItem>
            <h2>
              <AccordionButton
                minH={accordianHeight}
                _expanded={{ bg: highlightColor, color: highlightTextColor }}
                style={accordionButtonStyle}
              >
                <Box fontSize={"2xl"} flex="1" textAlign="left">
                  What is the liquidation threshold when borrowing?
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Text mb={2}>
                The liquidation threshold refers to the critical point at which
                a borrower{"'"}s collateral is automatically sold or
                &quot;liquidated&quot; to repay the borrowed asset. The
                threshold varies by pool, with each having its own specific
                limit. For current liquidation details for all pools, please
                visit this link:
                <Text color={colorMode === "light" ? "brand.600" : "brand.400"}>
                  <a
                    rel="noreferrer"
                    href="https://duckpools.notion.site/duckpools/4b5df7ab8bc54e3bad182221be65c69a?v=3afd7d81ab464fcd9afd9f5f989503c0&p=747612c093274809942613e173362ffd&pm=s"
                    target={"_blank"}
                  >
                    {`https://duckpools.notion.site/duckpools/4b5df7ab8bc54e3bad182221be65c69a?v=3afd7d81ab464fcd9afd9f5f989503c0&p=747612c093274809942613e173362ffd&pm=s`}
                  </a>
                </Text>
              </Text>
            </AccordionPanel>
          </AccordionItem>
        </Accordion>
      </Box>
    </div>
  );
}

export default Faq;
